# Generated by Django 4.2.24 on 2025-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockapp", "0002_product_category"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="stockapp_ca_name_204050_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="stockapp_pr_name_5b54a1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="stockapp_pr_price_c037d3_idx"),
        ),
    ]
