"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&m2e84(6p@!kr@)t#zhm25p&64l)4%#lp#k=1)9-h77^!g0#@n"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 

ALLOWED_HOSTS = ["nexus-ecommerce-backend-d8r3.onrender.com", "127.0.0.1", "localhost"]



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "accounts", 
    "stockapp",
    "django_filters",
    "drf_spectacular",
    "orders",

]   
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

from decouple import config
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG")
#database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # ✅ use postgres backend
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default=5432, cast=int),
    }
}

#databasewith postgres

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#authentication
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "config.utils.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

# src/config/settings.py




#pagination
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10 , # default page size,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
#pagination

#swagger documentation
# SPECTACULAR_SETTINGS = {
#     "TITLE": "Nexus Ecommerce API",
#     "DESCRIPTION": "API documentation for the Nexus Ecommerce backend",
#     "VERSION": "1.0.0",
#     "SERVE_INCLUDE_SCHEMA": False,
# }


SPECTACULAR_SETTINGS = {
    'TITLE': 'Nexus E-commerce API',
    'DESCRIPTION': """
Welcome to the **Nexus E-commerce API** documentation!

Here’s how you can use it:

### 🔑 Authentication
- Obtain a JWT token at `/api/auth/token/` using your username & password.
- Use the token in the `Authorization` header like:
Authorization: Bearer <your_token>

markdown
Copy code

### 📦 Products & Categories
- `/api/products/` → List, create, search, and filter products.
- `/api/categories/` → Manage product categories.

### 🛒 Cart & Orders
- `/api/cart/` → View or update your cart.
- `/api/orders/` → Create or view your orders.

---

 **Note:** Some endpoints require authentication.
  """,
  'VERSION': '1.0.0',
  'SERVE_INCLUDE_SCHEMA': False,
}


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
