# Generated by Django 4.2.24 on 2025-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="orders_orde_user_id_37fed6_idx"
            ),
        ),
    ]
